### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [oscar-broman/PAWN-Boilerplate#49]
That's the best I've ever seen for samp, except for the library from YSI Y_Less.

Why did you stop the development?
Have you lost interest?
Or perhaps not enough support?

**Comment by oscar-broman** [comment]
I was going to use it for a big project but it died out.

It still works just fine, you just need to do some updates to some include files.

**Comment by Jonathan-Rosewood** [comment]
The idea understood.
Thanks for the info, I'll try to keep up to date :)
